<?php

const DEFAULT_SCREEN_WIDTH = 170;
const DEFAULT_SCREEN_HEIGHT = 36;
const DEFAULT_DIALOG_WIDTH = 50;
const DEFAULT_DIALOG_HEIGHT = 3;
const DEFAULT_SELECT_DIALOG_WIDTH = 30;
const DEFAULT_DIALOG_X_POSITION = 0;
const DEFAULT_DIALOG_Y_POSITION = 0;
const DEFAULT_FPS = 60;
const DEFAULT_ASSETS_PATH = 'assets';
const DEFAULT_LOGS_DIR = 'logs';
const DEFAULT_LOG_LEVEL = 'debug';
const DEFAULT_SPLASH_TEXTURE_PATH = DEFAULT_ASSETS_PATH . '/splash.texture';
const DEFAULT_SPLASH_SCREEN_DURATION = 3;
const DEFAULT_WINDOW_WIDTH = 80;
const DEFAULT_WINDOW_HEIGHT = 30;