<?php

namespace Sendama\Engine\IO\Enumerations;

/**
 * KeyCode is an enumeration of key codes.
 */
enum KeyCode: string
{
  case ENTER      = 'enter';
  case SPACE      = 'space';
  case TAB        = 'tab';
  case BACKSPACE  = 'backspace';
  case ESCAPE     = 'escape';
  case DELETE     = 'delete';
  case UP         = 'up';
  case DOWN       = 'down';
  case RIGHT      = 'right';
  case LEFT       = 'left';
  case F0         = 'f0';
  case F1         = 'f1';
  case F2         = 'f2';
  case F3         = 'f3';
  case F4         = 'f4';
  case F5         = 'f5';
  case F6         = 'f6';
  case F7         = 'f7';
  case F8         = 'f8';
  case F9         = 'f9';
  case F10        = 'f10';
  case F11        = 'f11';
  case F12        = 'f12';
  case F13        = 'f13';
  case F14        = 'f14';
  case F15        = 'f15';
  case F16        = 'f16';
  case F17        = 'f17';
  case F18        = 'f18';
  case F19        = 'f19';
  case F20        = 'f20';
  case DO         = 'do';
  case FIND       = 'find';
  case HELP       = 'help';
  case INSERT     = 'insert';
  case END        = 'end';
  case HOME       = 'home';
  case NEXT       = 'next';
  case PREVIOUS   = 'previous';
  case SELECT     = 'select';
  case PAGE_UP    = 'page_up';
  case PAGE_DOWN  = 'page_down';
  case a          = 'a';
  case b          = 'b';
  case c          = 'c';
  case d          = 'd';
  case e          = 'e';
  case f          = 'f';
  case g          = 'g';
  case h          = 'h';
  case i          = 'i';
  case j          = 'j';
  case k          = 'k';
  case l          = 'l';
  case m          = 'm';
  case n          = 'n';
  case o          = 'o';
  case p          = 'p';
  case q          = 'q';
  case r          = 'r';
  case s          = 's';
  case t          = 't';
  case u          = 'u';
  case v          = 'v';
  case w          = 'w';
  case x          = 'x';
  case y          = 'y';
  case z          = 'z';
  case A          = 'A';
  case B          = 'B';
  case C          = 'C';
  case D          = 'D';
  case E          = 'E';
  case F          = 'F';
  case G          = 'G';
  case H          = 'H';
  case I          = 'I';
  case J          = 'J';
  case K          = 'K';
  case L          = 'L';
  case M          = 'M';
  case N          = 'N';
  case O          = 'O';
  case P          = 'P';
  case Q          = 'Q';
  case R          = 'R';
  case S          = 'S';
  case T          = 'T';
  case U          = 'U';
  case V          = 'V';
  case W          = 'W';
  case X          = 'X';
  case Y          = 'Y';
  case Z          = 'Z';
}
